### ISSUE TITLE
Publish package for addon repo

### ISSUE THREAD

**Issue by rzr** [rzr/sense-hat-webthing#3]
Installing dependencies on device using pip is currently failing on missing libs for numpy

The headers or library files could not be found for jpeg,

**Comment by rzr** [comment]
May action triggered by @mrstegeman  again it failed on fetch:

https://github.com/mozilla-iot/addon-builder/runs/653694149

https://github.com/mozilla-iot/addon-builder/pull/51

**Comment by mrstegeman** [comment]
Yes, I can trigger the proper build manually if you're ready for release. Can you go ahead and open a PR for the addon-list with the new add-on? I can fill in the URLs and checksums.

**Comment by rzr** [comment]
OK, let's rebuild next version I will make a new PR to update submodule in builder, will the list be updated automatically when using builder ?

**Comment by mrstegeman** [comment]
You don't need to update the submodule, it's done automatically. You just need to submit a PR or issue to the addon-list when you want it updated and I'll manually kick off a build of the new version.

**Comment by rzr** [comment]
For the record pip 10+ is needed to build package: 
earlier versions will fail on numpy and log: 
```
ImportError: No module named 'Cython'
```

Relate-to: https://github.com/rzr/sense-hat-webthing/pull/6

**Comment by mrstegeman** [comment]
This is finally building with the addon-builder, so we can do that for 0.0.5.

https://github.com/mozilla-iot/addon-builder/actions/runs/100116602

**Comment by rzr** [comment]
Ok I am releasing

**Comment by rzr** [comment]
It built, According to builder log 
https://github.com/mozilla-iot/addon-builder/runs/659606718?check_suite_focus=true

I expected it be published at:
https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/sense-hat-adapter-0.0.5-linux-arm-v3.7.tgz

@mrstegeman , Am I missing something to update:
https://github.com/mozilla-iot/addon-list/pull/827

**Comment by rzr** [comment]
Thanks @mrstegeman I think the flow is validated, Maybe I should make my PR editable or use a hook that would fetch binaries to update checksums and refresh PR, but it can be done manually for now, Probably github actions could do this on pushed tags too.

**Comment by mrstegeman** [comment]
Yeah... I’ve been trying to figure out a streamlined way of doing this, but it’s tricky to do without giving random people access to our S3 buckets and CI workflows.
